//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLS__.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JLS__.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   브라우저 속성 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string browcfg {
            get {
                return ResourceManager.GetString("browcfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이러한 정보는 웹서버에 Headless브라우저를 사용하지 않는 척 하기 위해 사용하는 설정들입니다.
        ///필요에 따라 설정하세요. 잘못 설정하면 프로그램이 제대로 구동하지 않을 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string browExplain {
            get {
                return ResourceManager.GetString("browExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   브라우저 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string browserSetting {
            get {
                return ResourceManager.GetString("browserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이 설정을 켜면 프로그램 시작시 서버와 통신이 완료 되기 이전 캐시데이터를 우선적으로 표시합니다.
        ///과거 숙제의 경우 통신을 시도하기 전 캐시데이터를 확인하여 캐시데이터를 사용할 수 있는 경우 통신을 진행하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string cacheExplain {
            get {
                return ResourceManager.GetString("cacheExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   캐시 우선 사용하기 :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string cachePrio {
            get {
                return ResourceManager.GetString("cachePrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   캐시데이터 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string cacheSetting {
            get {
                return ResourceManager.GetString("cacheSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   크롤링 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string crawlSetting {
            get {
                return ResourceManager.GetString("crawlSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   날짜:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JLS++의 모든 정보는 데이터베이스로 관리됩니다.
        ///위의 설정으로 데이터베이스를 직접 관리할 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string dbExplain {
            get {
                return ResourceManager.GetString("dbExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DATABASE 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string dbSetting {
            get {
                return ResourceManager.GetString("dbSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   캐시데이터 모두 지우기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string delCache {
            get {
                return ResourceManager.GetString("delCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과거 과제 내용을 포함하여 본 기기에 저장된 과제 데이터를 모두 지웁니다. 프로필은 초기화되지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string delCacheExplain {
            get {
                return ResourceManager.GetString("delCacheExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JLS++는 정상어학원의 숙제 확인의 귀찮음에 고통받는
        ///한 잼민이 프로그래머가 개발한 프로그램입니다.
        ///이 프로그램이 여러분의 과제 수행에 도움이 되었으면 합니다!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string explain {
            get {
                return ResourceManager.GetString("explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가짜 플러그인 사용 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string fakeplugin {
            get {
                return ResourceManager.GetString("fakeplugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램이 시작할때 서버에서 데이터 받기 :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string getOnStart {
            get {
                return ResourceManager.GetString("getOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPU 가속 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string gpu_acc {
            get {
                return ResourceManager.GetString("gpu_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JLS++에 온걸 환영합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string greeting {
            get {
                return ResourceManager.GetString("greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string hws {
            get {
                return ResourceManager.GetString("hws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로필 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string profSetting {
            get {
                return ResourceManager.GetString("profSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string pwd {
            get {
                return ResourceManager.GetString("pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재접속과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string recon {
            get {
                return ResourceManager.GetString("recon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과제 새로고침과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string refres {
            get {
                return ResourceManager.GetString("refres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장 경로 :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string savpath {
            get {
                return ResourceManager.GetString("savpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JLS++는 귀하의 개인정보를 소중하게 여깁니다.
        ///위와 같은 정보는 귀하의 기기에만 저장되며
        ///로그인시 JLS 서버 외에는 외부로 전송되지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string secExplain {
            get {
                return ResourceManager.GetString("secExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로필을 설정하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string setProf {
            get {
                return ResourceManager.GetString("setProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   창 보이기 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string shwWin {
            get {
                return ResourceManager.GetString("shwWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스토리지 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string storageSetting {
            get {
                return ResourceManager.GetString("storageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과제를 불러오지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string unlad {
            get {
                return ResourceManager.GetString("unlad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Agent : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string usr_agent {
            get {
                return ResourceManager.GetString("usr_agent", resourceCulture);
            }
        }
    }
}
