//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLS__ {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JLS__.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 브라우저 속성 설정.
        /// </summary>
        public static string browcfg {
            get {
                return ResourceManager.GetString("browcfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이러한 정보는 웹서버에 Headless브라우저를 사용하지 않는 척 하기 위해 사용하는 설정들입니다.
        ///필요에 따라 설정하세요. 잘못 설정하면 프로그램이 제대로 구동하지 않을 수 있습니다..
        /// </summary>
        public static string browExplain {
            get {
                return ResourceManager.GetString("browExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 브라우저 설정.
        /// </summary>
        public static string browserSetting {
            get {
                return ResourceManager.GetString("browserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이 설정을 켜면 프로그램 시작시 서버와 통신이 완료 되기 이전 캐시데이터를 우선적으로 표시합니다.
        ///과거 숙제의 경우 통신을 시도하기 전 캐시데이터를 확인하여 캐시데이터를 사용할 수 있는 경우 통신을 진행하지 않습니다..
        /// </summary>
        public static string cacheExplain {
            get {
                return ResourceManager.GetString("cacheExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 캐시 우선 사용하기 :.
        /// </summary>
        public static string cachePrio {
            get {
                return ResourceManager.GetString("cachePrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 캐시데이터 설정.
        /// </summary>
        public static string cacheSetting {
            get {
                return ResourceManager.GetString("cacheSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 크롤링 설정.
        /// </summary>
        public static string crawlSetting {
            get {
                return ResourceManager.GetString("crawlSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 날짜:.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JLS++의 모든 정보는 데이터베이스로 관리됩니다.
        ///위의 설정으로 데이터베이스를 직접 관리할 수 있습니다..
        /// </summary>
        public static string dbExplain {
            get {
                return ResourceManager.GetString("dbExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATABASE 설정.
        /// </summary>
        public static string dbSetting {
            get {
                return ResourceManager.GetString("dbSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 캐시데이터 모두 지우기.
        /// </summary>
        public static string delCache {
            get {
                return ResourceManager.GetString("delCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 과거 과제 내용을 포함하여 본 기기에 저장된 과제 데이터를 모두 지웁니다. 프로필은 초기화되지 않습니다..
        /// </summary>
        public static string delCacheExplain {
            get {
                return ResourceManager.GetString("delCacheExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JLS++는 정상어학원의 숙제 확인의 귀찮음에 고통받는
        ///한 잼민이 프로그래머가 개발한 프로그램입니다.
        ///이 프로그램이 여러분의 과제 수행에 도움이 되었으면 합니다!.
        /// </summary>
        public static string explain {
            get {
                return ResourceManager.GetString("explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 가짜 플러그인 사용 : .
        /// </summary>
        public static string fakeplugin {
            get {
                return ResourceManager.GetString("fakeplugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로그램이 시작할때 서버에서 데이터 받기 :.
        /// </summary>
        public static string getOnStart {
            get {
                return ResourceManager.GetString("getOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU 가속 : .
        /// </summary>
        public static string gpu_acc {
            get {
                return ResourceManager.GetString("gpu_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JLS++에 온걸 환영합니다..
        /// </summary>
        public static string greeting {
            get {
                return ResourceManager.GetString("greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 과제.
        /// </summary>
        public static string hws {
            get {
                return ResourceManager.GetString("hws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID : .
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 언어 : .
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이름 : .
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로필 설정.
        /// </summary>
        public static string profSetting {
            get {
                return ResourceManager.GetString("profSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 비밀번호 : .
        /// </summary>
        public static string pwd {
            get {
                return ResourceManager.GetString("pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 재접속.
        /// </summary>
        public static string recon {
            get {
                return ResourceManager.GetString("recon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 과제 새로고침.
        /// </summary>
        public static string refres {
            get {
                return ResourceManager.GetString("refres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설정 초기화.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 저장 경로 :.
        /// </summary>
        public static string savpath {
            get {
                return ResourceManager.GetString("savpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JLS++는 귀하의 개인정보를 소중하게 여깁니다.
        ///위와 같은 정보는 귀하의 기기에만 저장되며
        ///로그인시 JLS 서버 외에는 외부로 전송되지 않습니다..
        /// </summary>
        public static string secExplain {
            get {
                return ResourceManager.GetString("secExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로필을 설정하세요..
        /// </summary>
        public static string setProf {
            get {
                return ResourceManager.GetString("setProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설정.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 창 보이기 : .
        /// </summary>
        public static string shwWin {
            get {
                return ResourceManager.GetString("shwWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 스토리지 설정.
        /// </summary>
        public static string storageSetting {
            get {
                return ResourceManager.GetString("storageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 과제를 불러오지 않았습니다..
        /// </summary>
        public static string unlad {
            get {
                return ResourceManager.GetString("unlad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agent : .
        /// </summary>
        public static string usr_agent {
            get {
                return ResourceManager.GetString("usr_agent", resourceCulture);
            }
        }
    }
}
